version: "3"

services:
  # test DB
  test-db:
    container_name: test-db
    build:
      context: ./db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_PASSWORD: password123
      MYSQL_DATABASE: wanted_pre_onboarding_test
      MYSQL_USER: user123
    ports:
      - "3307:3306"
    networks:
      - wanted-work
      
  # node app DB
  test-app:
    container_name: test-app
    build:
      context: .
      target: test
    ports:
      - "3001:3000"
    networks:
      - wanted-work
    restart: on-failure:6
    env_file:
      - .env.test
networks:
  wanted-work:
    


